export const SAVE_EMAIL = 'SAVE_EMAIL';
export const REQUEST_CURRENCY_API_SUCCESS = 'REQUEST_CURRENCY_API_SUCCESS';
export const REQUEST_CURRENCY_API_ERROR = 'REQUEST_CURRENCY_API_ERROR';
export const SEND_EXPENSE_SUCCESS = 'SEND_EXPENSE_SUCCESS';
export const SEND_EXPENSE_ERROR = 'SEND_EXPENSE_ERROR';
